### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Rudolfet** [NeleB54Gold/SteamGridBot#1]
"fr": {
		"aboutButton": "ℹ️ Informations",
		"aboutMessage": "<b>ℹ️ Informations</b>\n\n*️⃣ PHP: [0]\n📶 Host: <a href=\"https://hetzner.cloud/?ref=tQoUeYbvIstA\">Hetzner.cloud</a>\n👨🏻‍💻 Développeur: @NeleReal\n📢 Mises à jour: @NeleBotsUpdates\n🌐 Plus d'informations @NeleBots",
		"changeLanguage": "🔡 Changer de langue",
		"chooseGame": "🔎 Choisissez l'un des jeux proposés par les boutons situés en dessous de ce message:",
		"downloadButton": "⬇️ Télécharger",
		"helpButton": "🆘 Aide",
		"helpMessage": "<b>🆘 Page d'aide </b>/n Entrez le titre d'un jeu pour rechercher une image de couverture !",
		"instanceError": "❌ Une erreur s'est produite, veuillez réessayer plus tard...",
		"noGamesFound": "❌ Aucun jeu trouvé...",
		"photoInfo": "<b>ℹ️ Dimensions:</b> [0]px\n<b>✍️ Note:</b> [1]\n<b>👤 Auteur:</b> <a href='https://steamcommunity.com/profiles/[2]'>[3]</a>",
		"photoNotFound": "❓ La photo n'a pas été trouvée...",
		"requestPending": "⚠️ Demande en cours de traitement...",
		"startMessage": "Avec ce Bot, vous pouvez rechercher les images de couverture de n'importe quel jeu !",
		"typeGrids": "📒 Grilles",
		"typeHeroes": "🌆 Héros",
		"typeIcons": "🖼 Icônes",
		"typeLogos": "🪧 Logos"

**Comment by NeleB54Gold** [comment]
You could just ask the change from the language file, but it's okay, thank you
